# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/EndAlignment:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/LineLength:
  Max: 120

Rails/RefuteMethods:
  Enabled: false
